name: Debug build

on: [push, pull_request]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/playstore'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: ./gradlew test
    - run: ./gradlew assembleDebug -PdoNotStrip
